### ISSUE TITLE
Allow pasting of hex colours without leading '#'

### ISSUE THREAD

**Issue by tgoulder4** [juxtopposed/realtimecolors#10]
**Is your feature request related to a problem? Please describe.**
I was using this site and wanted to paste a colour in, but had to manually add the leading '#' before it recognised it as a colour. I know, such a pain :( 

**Describe the solution you'd like**
For input without #, add it

**Describe alternatives you've considered**

**Additional context**

**Comment by juxtopposed** [comment]
Great point. Just updated.

**Comment by juxtopposed** [comment]
It should work both ways... can you please provide some screenshots of what's causing the problem?

**Comment by Re3ker** [comment]
> It should work both ways... can you please provide some screenshots of what's causing the problem?

last time it wasn't allowing me to paste from clipboard when # was included. 
Seems to work now!
