### ISSUE TITLE
[Bug]: Export  Zip. Image: 0 Bytes

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- I went to the "Download" tab in export options.
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/cf73e1dd-ae8a-4502-b557-bc9e64432894)
- I downloaded it.
- I got a ZIP file, and I extracted it.
- I opened the image.
- It showed below:
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/8f9a2fd8-74ff-46f1-b09a-4232497b6563)
- I checked the file explorer. It showed "0 bytes".
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/061bc6cf-4f95-4b91-ac46-0a4db38fe3d8)

### Reproduction Steps

Reproduction steps are covered in bug description

### Expected behavior

I should have an image I can open (and see). It shouldn't be of 0 bytes.

### Device Info

- OS: Windows 10
- Browser: Microsoft Edge 120.0.2210.77 (Official build) (64-bit)

**Comment by juxtopposed** [comment]
This should be resolved now.
