### ISSUE TITLE
[Bug]:  the sponsor ad is being covered by the tools section and is not visible at all 

### ISSUE THREAD

**Issue by Amanghvxh** [juxtopposed/realtimecolors#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 the sponsor ad is being covered by the tools section and is not visible at all 

### Reproduction Steps

 the sponsor ad is being covered by the tools section and is not visible at all 

### Expected behavior

 the sponsor ad is being covered by the tools section and is not visible at all 

### Screenshots

 the sponsor ad is being covered by the tools section and is not visible at all 

### Device Info

 the sponsor ad is being covered by the tools section and is not visible at all 

### Additional context

 the sponsor ad is being covered by the tools section and is not visible at all

**Comment by juxtopposed** [comment]
Thanks for reporting. This is not a bug. It will be addressed in the next update.
