### ISSUE TITLE
Color picker is laggy when dragging the cursor through the palette

### ISSUE THREAD

**Issue by alexis39tt** [juxtopposed/realtimecolors#12]
**Describe the bug**
The color picker is laggy when trying to drag it through the palette

**To Reproduce**
1. Open one of the color pickers at the bottom
2. Drag the cursor while selecting a color
3. The drag behaviour is not smoooth 

**Expected behavior**
The dragging should not be that laggy

**Screenshots**
No need

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 113.0.5672.93

**Comment by juxtopposed** [comment]
This is likely resolved since the custom colorpicker has just been released. Check it out and let me know if it looks good!
