### ISSUE TITLE
Ability to lock a color in randomize option 

### ISSUE THREAD

**Issue by ravi-sankarp** [juxtopposed/realtimecolors#13]
Right now there is an option for selecting random colors on the fly.
It would be very useful if we are able to lock in a some colors and randomize the rest of the colors.
A lock button next to the color would be useful.
On clicking the lock button the color would be locked.
The next time the user click on randomize only the rest of the colors would be changed, the locked one would not get changed.
In this way if the use likes a color they can lock the color they like and change the rest of the colors according to their wish.

**Comment by juxtopposed** [comment]
Hey there! Thanks for the submission. This feature has been [requested](https://github.com/juxtopposed/realtimecolors/issues/8) a couple of times before and will get released this week. Stay tuned!

**Comment by juxtopposed** [comment]
This has been released. Check it out live!
