### ISSUE TITLE
[BUG]: Complete black website when using space

### ISSUE THREAD

**Issue by ExampleWasTaken** [juxtopposed/realtimecolors#17]
**Describe the bug**
While playing around with the tool I repeatedly pressed space and ended up with an almost complete black website. As can be seen on the screenshot there is still a (very) slight variation between different elements.

**To Reproduce**
Steps to reproduce the behavior (this might be difficult):
1. Play around with the website (things like manually setting and locking colors)
2. Unlock all colors
3. Press space repeatedly. (It only took me 3-4 generation cycles but depending on the implementation of the color generation it might be virtually impossible to reproduce this.)
4. See nothing (black)

**Expected behavior**
Pretty obvious I think :)

**Screenshots**
![Screenshot 2023-05-16 at 02-28-25 Realtime Colors](https://github.com/juxtopposed/realtimecolors/assets/58574351/55f87263-2522-4125-831b-7410e9a684d1)

**Desktop (please complete the following information):**
 - OS: Window 10 Pro
 - Browser Firefox Developer Edition
 - 114.0b3 (64-bit)

**Comment by juxtopposed** [comment]
thanks for reporting! this should be resolved.
