### ISSUE TITLE
Improve Firefox compatibility with color picker

### ISSUE THREAD

**Issue by Malorn44** [juxtopposed/realtimecolors#18]
I'm not fully sure how easy or hard this would be to do but, currently, it is pretty annoying to use the palette generator tool and the realtime colors tool together. The color panel shown by firefox has no dropper tool.

If this is too difficult, another solution would be to just copy-paste the hex code from the generator tool to the realtime colors tool. However, it seems like copy-paste doesn't work here. I tested this on both firefox and edge browsers. Although $f2f2f2 (for example) might be on my clipboard, pressing ctrl+v or right clicking and pressing "paste" doesn't enter the hex code.

![Screenshot 2023-05-17 002759](https://github.com/juxtopposed/realtimecolors/assets/11843425/683afd68-dfc4-4f87-88ba-399acc72de83)

**Comment by juxtopposed** [comment]
The custom colorpicker has just been released, so you can see it on any browser. Check it out and let me know if it looks good!
