### ISSUE TITLE
Update Readme( Screenshots && ProductHunt )

### ISSUE THREAD

**Issue by Devansh-365** [juxtopposed/realtimecolors#20]
**Is your feature request related to a problem? Please describe.**
There is no screenshot & product hunt link in the readme.

**Describe the solution you'd like**
I see that people mostly put screenshots & product hunt links in the GitHub repo since users might discover these projects from GitHub and then they go to product hunt directly for upvotes and screenshots might be visually appealing to make users open the URL.

_Thank you for considering this feature request issue._

**Comment by juxtopposed** [comment]
Thanks for the suggestions. It's updated now.
