### ISSUE TITLE
Feature request: add export options for other color systems such as HSL, RGB, etc.

### ISSUE THREAD

**Issue by AmroKSaleh** [juxtopposed/realtimecolors#21]
Using the color picker you can use your preferred color system to input the color but when exporting all the colors as (CSS, SCSS, etc.) it would be greatly helpful to have the conversion from HEX to other systems such as HSL, RGB, etc.

**Comment by juxtopposed** [comment]
Just released this feature. Check it out and let me know if it looks good!
