### ISSUE TITLE
Secondary button color should not apply to background sections

### ISSUE THREAD

**Issue by DannyBen** [juxtopposed/realtimecolors#22]
The Secondary Button color is also applied to some backgrounds. I don't believe this is how most people use a secondary button color. In my view, this color should only apply to buttons.

That said, it would be helpful to have a Secondary Background color.

**Comment by juxtopposed** [comment]
In the last update (just now), we have a Secondary color instead of a secondary button color. I think adding an extra secondary background would make it just a little complex. But still, requires digging a bit deeper.
