### ISSUE TITLE
Dark - Light modes changes locked colors

### ISSUE THREAD

**Issue by scorixear** [juxtopposed/realtimecolors#23]
**Describe the bug**
When locking colors in light mode, colors get switched to a different version up on switching to dark mode.
After switching back to light mode, the original colors are not restored (but are kind of washed out).

This affected the secondary and accent color.

**To Reproduce**
1. Lock primary, secondary and accent when in light mode
2. Switch to dark mode (by clicking on the button)
3. Switch back to light mode

**Expected behavior**
Original locked colors should be restored.
I don't mind that dark mode switches to more suitable colors even when they are locked.
But the original colors should be restored when switching back.

**Desktop:**
- Browser: Firefox (115.0.2)
- OS: Windows 11

**RealTimeColors Version**
July 11, 2023

**Comment by juxtopposed** [comment]
Hey there, this should be updated. Check it out!
