### ISSUE TITLE
Better Tailwind Color Export

### ISSUE THREAD

**Issue by that-ambuj** [juxtopposed/realtimecolors#24]
**Is your feature request related to a problem? Please describe.**
The problem with tailwind is that you can't dynamically lighten or darken custom colors at will in your CSS.

**Describe the solution you'd like**
I would like a feature that would be a hybrid of the `shades` and `tailwind` export feature but just for tailwind. As described in the [TailwindCSS docs](https://tailwindcss.com/docs/customizing-colors#color-object-syntax), new colors should be a table of values from 50 through 950 with a color code for each shade; So that when creating buttons and stuff we can use class like `bg-primary-400 hover:bg-primary-500` that would increase it's darkness based on the table we just talked about. Currently, the tailwind export features feels lacking in the way that it simply gives out hex values instead of each shade of the needed color.

**Describe alternatives you've considered**
None yet, But I will update this issue if I come up with any.

**Additional context**
None

**Comment by juxtopposed** [comment]
Hey there! This makes a lot of sense. Will work on it.
Stay tuned :)

**Comment by ArjixWasTaken** [comment]
+1 On this, but not specific to tailwind, this can be used in more places.

For example [Mantine](https://mantine.dev/theming/colors) also supports various shades per colour in the theme.

**Comment by that-ambuj** [comment]
> +1 On this, but not specific to tailwind, this can be used in more places.
> 
> For example [Mantine](https://mantine.dev/theming/colors) also supports various shades per colour in the theme.

@juxtopposed please note, in case of Mantine UI, the colors shades are expected to be in an array of increasing darkness rather than a table of 50-900 like tailwind. Just a heads up if you plan on making it work for Mantine too. Thanks again for your great work!

**Comment by pyscripter99** [comment]
I would really like to see this. This feature would save me a lot of time.

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
