### ISSUE TITLE
Undo/Redo can be triggered while on text input is on focus

### ISSUE THREAD

**Issue by gczark** [juxtopposed/realtimecolors#26]
Text Input under Fonts > Text > Enter Font, when in focus can trigger undo/redo with left/right button.

**Comment by Gamer2070** [comment]
this also happens during exporting, while changing the file name

**Comment by Gamer2070** [comment]
it works on firefox now, but on operagx it still seems to be a problem (i dont have chrome downloaded so can't comment on that)

**Comment by juxtopposed** [comment]
Arlight, seems like I finally need to download opera gx and try this.
