### ISSUE TITLE
Copy link bug

### ISSUE THREAD

**Issue by SakeyJakey** [juxtopposed/realtimecolors#28]
**Describe the bug**
When you try to share the link, it says "Copied!Copied!"

**To Reproduce**
1. Go to any page on the site
2. Click on share link

**Expected behavior**
It should say "Copied!" once.

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/55712803/7c7815aa-258f-4d7e-bd6b-14333bde32e0)

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: iOS 14.7.1
 - Browser: Safari
 - Version: I do not know where to find this

**Comment by juxtopposed** [comment]
Thanks for the feedback! This is resolved now.
