### ISSUE TITLE
Export option for shades

### ISSUE THREAD

**Issue by Alties-GamingYT** [juxtopposed/realtimecolors#33]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Export option to export all shades of the colors in RGB, HEX, HSL
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by FinnRG** [comment]
I would also like to request this feature. Context: Mantine (a react component library) requires shades as an array of hex colors: https://mantine.dev/theming/colors/#adding-extra-colors.

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
