### ISSUE TITLE
Font size rations in the export function

### ISSUE THREAD

**Issue by byhartvig** [juxtopposed/realtimecolors#34]
It would be great if, in the future, when exporting, one could choose font-size ratios, similar to what they have on Typescale.com. This would be especially useful for exporting to frameworks like TailwindCSS and would save users a lot of time by automatically updating their config files.

I think font-size ratios could have the following scales:
1.250 - Major Third
1.333 - Perfect Fourth
1.500 - Perfect Fifth
1.618 - Golden Ratio

And of course, with a nice UI, as we can see you're capable of ;-)

**Comment by byhartvig** [comment]
And i meant "Font size **ratios** in the export function"

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
