### ISSUE TITLE
Responsive design breaks a little right after breakpoint

### ISSUE THREAD

**Issue by NoFailer** [juxtopposed/realtimecolors#35]
**Describe the bug**
If you use a browser and go into the mobile view and set the width to 1101 px the bottom toolbar breaks a little. The buttons go outside the viewport on both sides.

**To Reproduce**
1. Go to your browser tools and enable mobile view.
2. Either shrink the viewport down to 1101 px by dragging or just type the width in directly in the field on the top.
3. Look at the bottom toolbar.
4. See that the "text" button + colour picker as well as the "fonts" button on the opposite side are not fully visible/accessible.

**Expected behavior**
I expect the toolbar to stay inside the viewport and scale to the width of the viewport or wrap.

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/53854947/ecc2ac68-051f-4017-9ffb-2d62a016dba7)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 114.0.5735.199 (Official Build) (64-bit)

**Additional context**
Adding "flex-wrap: wrap" to the toolbar seems to solve the issue but it ain't the prettiest.
Here is a screenshot of what it would look like:
![image](https://github.com/juxtopposed/realtimecolors/assets/53854947/eaaacd3c-fc56-4a2f-b94d-ee2eecec1f7e)

**Comment by juxtopposed** [comment]
This is updated in v3.3.
