### ISSUE TITLE
[FEATUREs:4] Color cloning, @media css export, HTML importing, Color picker real-time update

### ISSUE THREAD

**Issue by highghlow** [juxtopposed/realtimecolors#41]
**Is your feature request related to a problem? Please describe.**
 - [feature:3] I try to see how colors would look on my own website and it takes a lot of time
 - [feature:4] I always use the color picker while looking at the page and it doesn't update in real-time, only when I click off the color picker

**Describe the solution you'd like**

 - [feature:1] Add the ability to clone colors (for example: secondary cloned to primary, primary cloned to text, etc.)
 - [feature:2] [DONE] Add an option to css export to use @media (prefers-color-scheme: dark/light) and export both light and dark version at the same time
 - [feature:3] [wontfix] Add the ability to import html files onto the website
 - [feature:4] [DONE] Make the color picker update the page in real-time (while setting the color) 

**Describe alternatives you've considered**
 - [feature:3] Maybe create realtimecolors as a tampermonkey script?

**Additional context**

 - feature;4
https://github.com/juxtopposed/realtimecolors/assets/132668972/2c437199-3d8d-4cf3-aad9-6a95c54d7d27

**Comment by juxtopposed** [comment]
Hi there. 

feature 1. Yes definitely will add in the next releases.
feature 2, Also good suggestion
feature 3. this is alright. I also feel like an extension would be more efficient than importing html files though.
feature 4. that option was available but since the colorpicker used to be a bit laggy (lots of elements to update at the same time), I switched to this. will see about it.

Thanks for the suggestions. Will update here once released.

**Comment by highghlow** [comment]
> feature 4. that option was available but since the colorpicker used to be a bit laggy (lots of elements to update at the same time), I switched to this. will see about it.

Thanks for the reply. Maybe real-time updating could be added as an optional setting.

**Comment by juxtopposed** [comment]
Hey there, feature #4 should be updated. Now you don't have to click off the color picker. Releasing the mouse alone will work. Check it out!

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
