### ISSUE TITLE
[Feature] WPF XAML color export

### ISSUE THREAD

**Issue by SeizureSaladd** [juxtopposed/realtimecolors#42]
**Is your feature request related to a problem? Please describe.**
A nice feature to have would be exporting to XAML SolidColorBrush as I make WPF C# desktop applications. Although I feel as if Realtime Colors is probably more suited for website development, I think the color palettes would still work within desktop applications and would still look pretty nice.

**Describe the solution you'd like**
Add an option to export a palette to XAML. Example below:
```xml
<SolidColorBrush x:Key="Text" Color="#00030f"/>
<SolidColorBrush x:Key="Background" Color="#dce2fe"/>
<SolidColorBrush x:Key="Primary" Color="#0528c2"/>
<SolidColorBrush x:Key="Secondary" Color="#cdd6fe"/>
<SolidColorBrush x:Key="Accent" Color="#0633f9"/>
```

**Describe alternatives you've considered**
Could just do it manually but that's pretty tedious.

**Additional context**
I'm pretty sure that SolidColorBrush only natively supports hex codes and whatever the hell [scRGB](https://en.wikipedia.org/wiki/ScRGB) is. More about SolidColorBrush [here](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.solidcolorbrush?view=windowsdesktop-7.0).

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
