### ISSUE TITLE
[BUG] Menu failure after window resizing

### ISSUE THREAD

**Issue by highghlow** [juxtopposed/realtimecolors#43]
**Describe the bug**
If you shrink the window horizontally until the menu style switches to mobile, then open colors or fonts submenu and expand the window, the menu breaks
[Desktop only]

**To Reproduce**
1. Shrink the window horizontally until mobile style activates
2. Open one of the submenus 
3. Expand the window back
4. The menu disappears

**Expected behavior**
The menu should be visible after the windows resizes back

**Screenshots**
Currently unable to add screenshots. Will add soon

**Desktop (please complete the following information):**
 - OS: Fedora linux
 - Browser: Firefox
 - Version: 114.0.1
This issue probably isn't browser specific

**Smartphone (please complete the following information):**
This issue is desktop only

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
