### ISSUE TITLE
[FEATUREs:2] Custom export formats, Font dropdown

### ISSUE THREAD

**Issue by highghlow** [juxtopposed/realtimecolors#45]
**Is your feature request related to a problem? Please describe.**
 - [feature 1] Many people ask for adding of some new export formats, but there are a lot of them and you wouldn't be able to add all of them
 - [feature 2] Searching for local fonts is a bit hard

**Describe the solution you'd like**
 - [feature 1]
Add some way of creating custom export formats. Maybe a text box where you can write text to be exported with some way of inserting actual colors. For example:
```
<SolidColorBrush x:Key="Text" Color="${text.current.hex}"/> <SolidColorBrush x:Key="Background" Color="${color.background.current.hex}"/> <SolidColorBrush x:Key="Primary" Color="${color.primary.hex}"/>
```
The color replacement strings could look like: `${color.(text/primary...).(hex/css-rgb...)} `
 - [feature 2] Maybe add a dropdown with commonly/previously used fonts

**Additional context**
Feature bombardment

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
