### ISSUE TITLE
Export functionality and Share link functionality is not working.

### ISSUE THREAD

**Issue by MitraKumar** [juxtopposed/realtimecolors#47]
**Describe the bug**
After generating the color on the [home page](https://realtimecolors.com/?colors=011e11-e6fef4-1105bd-fda5cb-c3d105) when trying to export or to use share link feature is not working. An error is coming on console when clicking on the Share link button `Uncaught ReferenceError: copyPageUrl is not defined`

**To Reproduce**
1. Go to [hompage](https://realtimecolors.com/?colors=011e11-e6fef4-1105bd-fda5cb-c3d105)
2. Generate and randomize color
3. Click on Export or Share link button. Or use keyboard shortcut `Ctrl + E` or `Ctrl + S`

**Expected behavior**
On clicking the export button the colors generated should be exported and on clicking the Share link button the link should be copied.

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/36085636/a30660f1-51a0-49e2-b0a1-98ec0595e021)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 114.0.5735.199

**Comment by juxtopposed** [comment]
Hey! Thanks for reporting. This should be resolved now.

**Comment by MitraKumar** [comment]
Thanks for the quick fix @juxtopposed
