### ISSUE TITLE
Ctrl Q shortcut conflicts with Firefox

### ISSUE THREAD

**Issue by BeauTheBeau** [juxtopposed/realtimecolors#49]
**Describe the bug**
The keybind to toggle between dark/light mode (`Ctrl Q`), conflicts with the [Firefox shortcut to quit Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs)

**To Reproduce**
1. Open [Realtime Colours](https://realtimecolors.com/?) in Firefox 
2. Hit `Ctrl Q` 
3. Firefox will prompt you to Quit Firefox 
4. Realtime Colours hasn't switched dark mode :(

**Expected behavior**
Realtime Colors toggles between light & dark mode 

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Browser: Mozilla Firefox
 - Version: 116.0.2 (64-bit)

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
