### ISSUE TITLE
Dropdown menu for fonts

### ISSUE THREAD

**Issue by yaay** [juxtopposed/realtimecolors#50]
**Is your feature request related to a problem? Please describe.**
Dealing with the fonts option can be a little frustrating sometimes since you need to write the font name correctly and most of the time you need few quick options to choose and try fonts.

**Describe the solution you'd like**
A simple dropdown menu that has few popular fonts from Google Fonts.

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
