### ISSUE TITLE
FAQ section dropdowns not working on screen size greater than 1100px

### ISSUE THREAD

**Issue by riteshkumarldh** [juxtopposed/realtimecolors#52]
**Describe the bug**
FAQ section dropdowns not working on screen size greater than 1100px

**To Reproduce**
1. Go to https://realtimecolors.com/palettes/
2. Click on any faq questions answer will not show only screen greater than 1100px

**Expected behavior**
On click of question We can see the answers on larger screens also

Solution:
Hi, I have inspected the code and found you have set the max-height 80px on .faq class but after clicking on question you are not removing the max-height. So, either remove the max-height on .faq class but then there is no transition or you can set the max-height to a fix value like 400-500px in which content get fit. It will give smooth transition. pls note it is not working only screen size greater than 1100px

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
