### ISSUE TITLE
Support Exporting both Dark and Light mode

### ISSUE THREAD

**Issue by TejasBhovad** [juxtopposed/realtimecolors#53]
The site currently exports only light mode or only dark mode variables, it would be convenient to allow exporting both colors for dark and light mode together

Maybe add a toggle that would export both dark and light mode colors

Right now we have to rename the variables ourselves, its a good QOL change to implement

[I found this while exporting to tailwind but other export options can benefit equally]

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update!
