### ISSUE TITLE
So many performance drops

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [juxtopposed/realtimecolors#54]
**Describe the bug**
I get so many drops in which my browser freezes because of the website. Especially if I'm often switching the website and pasting some colors in.

**To Reproduce**
1. Switch websites
2. Copy some colors
3. Paste them in
4. Do it again
5. See error

**Expected behavior**
No freezing of the website

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge newest version (118)

**Comment by juxtopposed** [comment]
Hi there, please check out the changes in the new v3 update and let me know if it works!
