### ISSUE TITLE
Saving font settings in the URL

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#57]
**Is your feature request related to a problem? Please describe.**
It's frustrating when the selected font settings are not saved in the URL like colors are.
And the selected font settings get changed when I move to another page of site.

**Describe the solution you'd like**
Save the fonts selected for body and headings and also the type scale in the URL.

**Describe alternatives you've considered**
Always changing the font settings when I want to preview with those settings.

**Comment by juxtopposed** [comment]
Hi there, please check the updates in v3.1.
