### ISSUE TITLE
Local font names combobox suggestions

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#59]
You can get a list of local fonts on Chrome and Edge according to [caniuse.com](https://caniuse.com/?search=querylocalfonts):
```js
(await queryLocalFonts()).map(fontData => fontData.family)
```

If you want to, you may show these in the suggestion/autocomplete list while typing a font name.

**Comment by juxtopposed** [comment]
This is a very good suggestion, thank you!

**Comment by PositiveUser** [comment]
Check below image:
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/f019a381-ecf7-47f4-acd8-51491dfb70f3)

You should remove duplicates:
```js
[...new Set((await queryLocalFonts()).map(fontData => fontData.family))]
```

**Comment by juxtopposed** [comment]
Hi there, please check the updates in v3.1.
