### ISSUE TITLE
New feature : A contrast ratio calculation panel

### ISSUE THREAD

**Issue by PhakphumV** [juxtopposed/realtimecolors#6]
**Is your feature request related to a problem? Please describe.**
As a web designer, some clients may have a requirement to have their website compliance with WCAG on the text color contrast ratio.
Web Accessibility is becoming necessity for big corporations and even required by law in some countries.

**Describe the solution you'd like**
An off-canvas information panel, maybe on the left/right side, to display contrast ratio and whether the chosen colors are compliance with WCAG level AA or AAA.

**Additional context**
Here are description of Success Criterion for WCAG level AA and level AAA
https://www.w3.org/TR/WCAG21/#contrast-minimum
https://www.w3.org/TR/WCAG21/#contrast-enhanced

For contrast ratio calculation, I found this github repo that could be used as a reference
https://github.com/siege-media/contrast-ratio

**Comment by juxtopposed** [comment]
This feature is live now! Make sure to check it out.

**Comment by PhakphumV** [comment]
Cool, thank for your effort! Really appreciate!
