### ISSUE TITLE
Use only serif fonts while randomizing with font category "Serif"

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#68]
**Describe the bug**

![Image showing that the font category selected is Serif](https://github.com/juxtopposed/realtimecolors/assets/89864580/893eef5d-7672-479c-8987-8601a714fa11)

When the font category selected is "serif" and keep randomizing, I see it rarely actually uses a serif font.

List of some fonts I got while the font category selected was "Serif":
- Noto Sans Bamum
- Noto Sans Hebrew
- Hanken Grotesk
- Sofia Sans
- Carrois Gothic
- Noto Sans New Tai Lue
- Fredoka
- Zen Kurenaido
- Monomaniac One
- Hind Madurai
- Rosario
- Alegreya Sans
- Cuprum

None of the fonts mentioned in this list are serif fonts. Why?

**To Reproduce**

1. Set the font category to randomize in to "Serif"

![Image showing that the font category selected is Serif](https://github.com/juxtopposed/realtimecolors/assets/89864580/893eef5d-7672-479c-8987-8601a714fa11)

2. Randomize fonts

![Image showing Randomize button](https://github.com/juxtopposed/realtimecolors/assets/89864580/b4212463-81f1-4836-a88b-d04c174385f7)

4. Find that many fonts aren't serif fonts.

![Image showing that the page isn't using a serif font](https://github.com/juxtopposed/realtimecolors/assets/89864580/747e0b17-d7f1-41a8-9de9-70aa4b0672a6)

**Expected behavior**
If the font category selected is "Serif", use only serif fonts when randomizing.

**Comment by juxtopposed** [comment]
Hi there, please check the updates in v3.1. This should work properly now.
