### ISSUE TITLE
Bug: Text color displays background color

### ISSUE THREAD

**Issue by F-PTS** [juxtopposed/realtimecolors#7]
**Describe the bug**
Text color badge is the same color as the background, not the text

**To Reproduce**
1. Go to https://realtimecolors.com/

**Expected behavior**
Text color box should have a color of the text

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/80021800/c22603d1-17e9-4f4c-88a6-a1e4f7d76e9b)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

**Comment by juxtopposed** [comment]
Hey! Thanks for the submission.

That's not a bug actually. The text box shows the 'Text' color as the text color you choose. It could be a little confusing to some if the text color of the word 'Text' itself is showing the background color or another color. Hope it makes sense :)

Cheers!

**Comment by F-PTS** [comment]
yeah change it
