### ISSUE TITLE
Fonts with numbers dont work

### ISSUE THREAD

**Issue by PcLover2** [juxtopposed/realtimecolors#70]
**Describe the bug**
A local font with a number in the name deosnt work

**To Reproduce**
![image](https://github.com/juxtopposed/realtimecolors/assets/106612743/4db597ea-424e-4454-8f80-e5c3ace4ea1c)
If i type a number it doesnt add it to the css, but if i add the number manually it does work.

**Expected behavior**
The font works

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge, chrome, brave
 - Version: newest as of 25/09

**Comment by juxtopposed** [comment]
Hi there, please check the updates in v3.1.
