### ISSUE TITLE
Individual color values: variables for custom export

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#72]
Like in HSL,
`hsl.s` or `hsl.saturation` can be `18%`,
but `hsl.s.number` or `hsl.saturation.number` would be `18` without the percentage (%) unit.

Kevin Powell gave a nice tip about separating values/sliders of HSL or any other thing like OKLCH.
[Check his video](https://www.youtube.com/watch?v=IHaT_rjC2gM&ab_channel=KevinPowell)

![](https://github.com/juxtopposed/realtimecolors/assets/89864580/53c73d0b-ab49-4b3a-94bd-b0e496522405)

Thank you

**Comment by juxtopposed** [comment]
Hi there, please check the updates in v3.1.
