### ISSUE TITLE
Tailwind color export base color and dark theme color beeing same

### ISSUE THREAD

**Issue by Vasu7777py** [juxtopposed/realtimecolors#74]
In Tailwind while exporting the color profile turning on shades and theme flags.
both base and dark theme colors will be the same

1. Create a color profile
2. Click on export with shades and theme flags turned on.
3. See both base and dark themes are the same.

Different color for base and dark theme.

base theme
![image](https://github.com/juxtopposed/realtimecolors/assets/65950340/e4d43773-7273-4b75-9925-31aa1f211987)

dark theme
![image](https://github.com/juxtopposed/realtimecolors/assets/65950340/4308a48a-a0f0-4f65-b548-0c7d2b3d1589)

 - OS: windows 11
 - Browser: firefox
 - Version: 117.0.1

**Comment by juxtopposed** [comment]
Hi there. This is mainly because the shades are the same in both modes. What would you suggest is a better way to show this?

**Comment by sa2812** [comment]
@juxtopposed - I'm too am tripped up by this. Shouldn't the dark shades be flipped with respect to the light shades?

In my code, I can have something like
```
<div class="bg-background-50">
```
and in dark mode, the `background` being referenced should be a different colour, but that's not how it currently works. It might be an implementation issue on my end, but I think that it's the same issue that @Vasu7777py encountered.

**Comment by juxtopposed** [comment]
This should be updated now. Let me know if it looks good.

**Comment by sa2812** [comment]
That's perfect @juxtopposed! Thanks for the quick turnaround! I'm not OP, but this issue looks like one you can safely close.
