### ISSUE TITLE
Upload local fonts to realtimecolors

### ISSUE THREAD

**Issue by Darrel-Santoso** [juxtopposed/realtimecolors#75]
**Is your feature request related to a problem? Please describe.**
Sometimes I use custom fonts downloaded to my PC and I want to upload them to realtimecolors to see if it will fit.

**Describe the solution you'd like**
Uploading custom fonts to the web via the font menu is nice

**Comment by juxtopposed** [comment]
You should be able to see your local fonts in the dropdown (if you've given access to the website, however this is only supported on Chrome and Edge for now). You can also just type the name of the font you have installed locally and load it on the site automatically.

**Comment by Darrel-Santoso** [comment]
I see, I was using firefox at the time and didn't see the font drop down to install custom fonts

**Comment by juxtopposed** [comment]
Got it. Closing as resolved.
