### ISSUE TITLE
Custom code export - shadcn - secondary foreground same as background

### ISSUE THREAD

**Issue by matijakelemen** [juxtopposed/realtimecolors#77]
**Describe the bug**
While exporting colors in Custom code -- shadcn format I'm getting the same color on secondary-foreground and secondary-background. Same goes for dark mode.
```
--secondary: 34 52% 14%;
--secondary-foreground: 34 52% 14%;
````
This page was used https://www.realtimecolors.com/?colors=362611-fbf1ea-f4ba1a-362611-443f92&fonts=Poppins-Poppins

**To Reproduce**
1. Go to https://www.realtimecolors.com/?colors=362611-fbf1ea-f4ba1a-362611-443f92&fonts=Poppins-Poppins
2. Click on Export
3. Click on Custom Code
4. Click on shadcn
6. See error mentioned above

**Expected behavior**
On inspecting the page, colors are like this in button Secondary:
background = hsl(34, 52%, 14%)
text = hsl(25, 68%, 95%)
This values should be exported.

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/26557433/b8edf99c-4aa4-47a5-8adc-00dcf46eb686)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 116

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
On the first look, it's exporting values of the background of the secondary as foreground, and not the background of the main page. Just a hint, may be wrong.

**Comment by juxtopposed** [comment]
This is fixed in v3.2.
