### ISSUE TITLE
Feature: Lock particular color from changing when randomizing

### ISSUE THREAD

**Issue by F-PTS** [juxtopposed/realtimecolors#8]
**Is your feature request related to a problem? Please describe.**
I have found the perfect color combination, but the accent color is not looking good. 
I'd like to change it, but I'm afraid to set the color manually.
I also can't randomize it because I will lose other colors that I like.

**Describe the solution you'd like**
I would love to toggle a “lock” on certain colors so that they don't change when I click randomize.

**Comment by juxtopposed** [comment]
Great suggestion, and I've received this request from many, so it will definitely be the next feature. Thanks for the submission!

**Comment by cchirag** [comment]
I forked the repo and pushed an update with this feature. The PR is deleted :(.

**Comment by juxtopposed** [comment]
This feature is planned for the next release this week. Stay tuned.

**Comment by juxtopposed** [comment]
This feature has been released. Check it out live!
