### ISSUE TITLE
Download button doesn't seem to do anything.

### ISSUE THREAD

**Issue by mrjimhubbard** [juxtopposed/realtimecolors#81]
**Describe the bug**
Download button doesn't download anything.

**To Reproduce**
see https://youtu.be/z-0xXxjCvJM for a screencast of the issue

**Expected behavior**
I expected the Download button to download a zip file of the colors and such that the site produces.

**Screenshots**
Again - https://youtu.be/z-0xXxjCvJM 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Version 22H2 OS Build 19045.3516
 - Browser: Chrome Version 117.0.5938.132 (Official Build) (64-bit)
 - Browser 2: Firefox 118.0.1 (64-bit)
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by juxtopposed** [comment]
This should be resolved now.
