### ISSUE TITLE
`Randomize Color` tooltip shows when hovering options

### ISSUE THREAD

**Issue by Snailedlt** [juxtopposed/realtimecolors#83]
**Describe the bug**
The `Randomize Color` tooltip is showing when you hover options

**To Reproduce**
1. Go to the homepage: https://www.realtimecolors.com/?colors=11191c-f9fafb-404868-dbd6e6-6c5b95&fonts=Poppins-Poppins
2. Click on the arrow next to the "Randomize Color" button
3. Hover over one of the options

**Expected behavior**
The tooltip is only shown when the user hovers the "Dice" icon, not options inside the select

**Screenshots**
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/c647e79f-b58e-4af5-aaeb-457c714500d6)
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/bbcc289e-4766-405d-864d-4ea1a8cb3c63)
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/4720d1ae-d40c-4a0c-a529-b83aa8d99756)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 117.0.5938.132 (Official Build) (64-bit)

**Additional context**

**Comment by juxtopposed** [comment]
This is updated now. Thanks for pointing it out.

**Comment by Snailedlt** [comment]
Nice, thanks for updating it so quickly!  I guess this issue can be closed as completed now then :)
