### ISSUE TITLE
Change from issue templates to issue forms

### ISSUE THREAD

**Issue by Snailedlt** [juxtopposed/realtimecolors#84]
**Is your feature request related to a problem? Please describe.**
Currently this GitHub project uses Issue templates which are not ideal for inputing information. The main reason is that comments have to be included in the same textfield that users write their issue description in. Also in the current issue templates comments are written in plain text. An alternative to issue templates is [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

**Describe the solution you'd like**
Use Issue forms instead of issue templates. Issue forms allow you to have multiple input fields, text outside of these input fields, and it allows you to automatically give issues a label based on which issue form is used.

**Describe alternatives you've considered**
Instead of writing comments in plain text, use comments so that they don't clutter up the issue in case people forget to remove them

**Additional context**
This is what it looks like with issue templates:
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/72d6ba6d-eb61-4bb9-a922-2c1362f9359e)
This is an example of an issue form: 
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/f7185b69-ff6d-481f-87e8-cc1e25d611f7)

If this sounds like a good idea to you, I could make a PR

**Comment by juxtopposed** [comment]
Sounds good.

**Comment by Snailedlt** [comment]
Neat! I'll start on the PR right away then
