### ISSUE TITLE
Add explanation to the tooltip of colors that fail color checks

### ISSUE THREAD

**Issue by Snailedlt** [juxtopposed/realtimecolors#85]
**Is your feature request related to a problem? Please describe.**
When color contrasts are not acceptable there's a small popover over the (x) icon like this: 
![image](https://github.com/juxtopposed/realtimecolors/assets/43886029/6d99be43-2fd1-48e2-9fb1-fcc8d49058ea)
As it stands it's really hard to know what `2.33:1` means without knowing that it's the contrast ratio.

**Describe the solution you'd like**
It would be nice if this popover was either clickable and took you to a page/website with more information on the issue (contrast ratio requirements)
- 

**Describe alternatives you've considered**
1. The tooltip shows another tooltip with an explanation as to what the problem is exactly. 
Perhaps it could just say what the minimum contrast ratio is... or perhaps it could link to a page that shows you what the requirements for the contrast ratio is?
2. Add a link to https://color.a11y.com/ and let them do the explaining... but you still need to let the user know that `2.33:1` is the contrast ratio

**Additional context**
I would take inspiration from other contrast ratio checker websites like these:
- https://www.siegemedia.com/contrast-ratio
- https://coolors.co/contrast-checker
- https://colourcontrast.cc/
- https://contrastchecker.com/

**Comment by PositiveUser** [comment]
whocanuse.com

**Comment by Snailedlt** [comment]
@PositiveUser Nice! That also might also be useful for #25 and #44

**Comment by juxtopposed** [comment]
A link is now included to the relevant Docs page.

**Comment by Snailedlt** [comment]
Great! The docs could be a bit more visual on this point, but that's another issue, so I'll close this one as complete.
Thanks for the awesome tools you're creating, and giving us for free!
