### ISSUE TITLE
[Bug]: Pick no-saturation color. Hue change to red (0°)

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#87]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Whenever I select a zero-saturation color like completely neutral grays, black or white in the color picker, it changes the hue to red (0°).

These no-saturation colors are present at the extreme left and bottom edges/corners.

### Reproduction Steps

Bug description

### Expected behavior

The hue should not change to red (0°) when picking a neutral, black or white gray.

### Screenshots

A few examples with black and white although neutral grays also cause the same issue.

https://github.com/juxtopposed/realtimecolors/assets/89864580/074c98fa-4793-4155-ac94-9f6b2adacc91

### Device Info

Not device-specific and browser-specific; Happens in all contexts.

**Comment by PositiveUser** [comment]
It changes the hue to red or zero degrees whenever a picked color doesn't have saturated.

Before:
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/2e71abf4-7762-4096-8b13-3317e38ab7d9)

After:
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/f211b29f-1a81-4005-950b-beba81171ae3)

In HSL, I set the saturation to 0, so it changed the hue to 0

**Comment by juxtopposed** [comment]
This should be resolved (v3.5)

**Comment by PositiveUser** [comment]
Not resolved

**Comment by PositiveUser** [comment]
> This should be resolved (v3.5)

Not resolved yet


> It changes the hue to red or zero degrees whenever a picked color doesn't have saturated.
> 
> Before: ![image](https://private-user-images.githubusercontent.com/89864580/273314366-2e71abf4-7762-4096-8b13-3317e38ab7d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTYzMzcsIm5iZiI6MTcwMjk1NjAzNywicGF0aCI6Ii84OTg2NDU4MC8yNzMzMTQzNjYtMmU3MWFiZjQtNzc2Mi00MDk2LThiMTMtMzMxN2UzOGFiN2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NTdhYWI4MmZiNjY0NmQxNzE4YjdiOTIzMjljYzlhMzkyZWQxNTBmZGQ5YTM1ZWVjZTE1Mzg3NjUzMmJiYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hxwo5FU5sAStBwDb86txbY0M2Hdrqxakx82bXwDYY0U)
> 
> After: ![image](https://private-user-images.githubusercontent.com/89864580/273314483-f211b29f-1a81-4005-950b-beba81171ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTYzMzcsIm5iZiI6MTcwMjk1NjAzNywicGF0aCI6Ii84OTg2NDU4MC8yNzMzMTQ0ODMtZjIxMWIyOWYtMWE4MS00MDA1LTk1MGItYmViYTgxMTcxYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzMjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlM2E5OWY0YzFmNzVlNjBjMDJmNGUyYmZhOWI5MzgwOWI1YmU5OGY1ZGRjMjk3M2Y4OWMwMGU5NWRjMjBlNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SsOH8X-gyfNeyZMsaT4LJBSrKeUgx0SkZ7NV2pp7Mhc)
> 
> In HSL, I set the saturation to 0, so it changed the hue to 0

Still happens

**Comment by PositiveUser** [comment]
But, if I use the above color picker instead of the below input, the bug is fixed here.

**Comment by juxtopposed** [comment]
The HSL input behavior is expected. Many colorpickers do the same. It's mostly because the lack of saturation returns the same color across all hues. I'll close this as the colorpicker's bug is resolved for now.
