### ISSUE TITLE
[Bug]: Font names match input only at start

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While I type in a font input, the fonts names shown/suggested only match at the start instead of matching the input anywhere in the font name. I don't quite like this.

Example:

I wanted "Playfair Display".

I typed "display" which the font name "Playfair Display" doesn't start with: I did not see "Playfair Display".

However, when I typed "playf" that font name / string "Playfair Display" does start with: I did see "Playfair Display".

### Reproduction Steps

(Bug description)

### Expected behavior

I want what I font input to match anywhere in the font names instead of just the start.

### Screenshots

:(
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/895f8473-1c14-4dae-a570-2e8bc0b3a470)

:)
![image](https://github.com/juxtopposed/realtimecolors/assets/89864580/d9920fb3-4bf8-4426-a699-d070995dc073)

### Device Info

Not specific to a browser/device

**Comment by Saigenix** [comment]
Can I solve this ?

**Comment by juxtopposed** [comment]
This is updated in v3.3.1

**Comment by PositiveUser** [comment]
More like below instead

```js
[
    ...fontsSuggestions
        .filter(s => s.toLowerCase().startsWith(input)),
    ...fontsSuggestions
        .filter(s => !s.toLowerCase().startsWith(input)),
]
```

A list where you show the font suggestions starting with the input first.

**Comment by juxtopposed** [comment]
The matched parts of the fonts now become bold in any part of the font name to help both with readability and increasing the reach and accuracy (v3.6). Let me know if it works.

**Comment by PositiveUser** [comment]
That can work
