### ISSUE TITLE
Font Input

### ISSUE THREAD

**Issue by SarcevicAntonio** [juxtopposed/realtimecolors#9]
I'm not clear on why we need to upload font files for the site to use fonts. The site should just take a font-family name and apply it to the CSS, so the browser can pick the font.

**Comment by juxtopposed** [comment]
You are right, and ultimately it will, in later versions.

Users can enter the font-family they have _installed_ on their device. For now, they'll be able to grab any font from the web (without the need to install it) and see how it looks.
