### ISSUE TITLE
[Bug]: Missing more than 34 properties when export color scheme to SkeletonUI

### ISSUE THREAD

**Issue by anhtuank7c** [juxtopposed/realtimecolors#90]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

missing the following properties from type 'ThemeProperties': '--theme-font-family-base', '--theme-font-family-heading', '--theme-rounded-base', '--theme-rounded-container', and 34 more.

### Reproduction Steps

1. Generate a new SvelteKit project which included SkeletonUI: `npm create skeleton-app@latest my-skeleton-app`, choose `TypeScript` template.
2. Go to realtimecolor to generate and export
3. Make a new theme file in `.ts` and paste the exported content from Skeleton options
4. import type from the top of theme file: `import type { CustomThemeConfig } from '@skeletonlabs/tw-plugin';`
5. Error appear.

### Expected behavior

Exported color scheme for Skeleton should satisfied `CustomThemeConfig`

import type { CustomThemeConfig } from '@skeletonlabs/tw-plugin';

### Screenshots

![image](https://github.com/juxtopposed/realtimecolors/assets/3163410/59f415ee-a2aa-47f6-8ad3-186255e5c29a)

### Device Info

* OS: MacOS
* Browser: Firefox
* Version: 118.0.1 (64-bit)

**Comment by juxtopposed** [comment]
Hi, this should be resolved now. Let me know if it works.
