### ISSUE TITLE
[Bug]: Undo features do not work after switching/changing pages in the site

### ISSUE THREAD

**Issue by PositiveUser** [juxtopposed/realtimecolors#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I cannot undo any colors or fonts after going to another page in the site (realtimecolors.com).

### Reproduction Steps

1. Change colors/font
2. Go to another page
3. You won't be able to undo anything.

### Expected behavior

I want to be able to undo things even after visiting another page.

Suggestion/Idea:
Save history of colors and fonts in `sessionStorage`

### Device/Browser Info

Not important

**Comment by juxtopposed** [comment]
This should be resolved now (in v3.5)
