### ISSUE TITLE
[Bug]: Body font does not update in 2 sections.

### ISSUE THREAD

**Issue by c00lkase** [juxtopposed/realtimecolors#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the "200K+ Users" and the "Free Forever" sections the body font does not update.

### Reproduction Steps

1. Go to 'Fonts'
2. Change the body font from 'Poppins'
3. Scroll down to the mentioned areas

### Expected behavior

The font to change

### Screenshots

![Untitled](https://github.com/juxtopposed/realtimecolors/assets/90591350/487b2a66-a142-4d7f-b581-0d6c7b121485)

### Device Info

- OS: Windows 10 Pro Version 10.0.19045 Build 19045
- Browser: Chrome
- Version: 118.0.5993.89 (Official Build) (64-bit)

**Comment by juxtopposed** [comment]
This is updated. Closing as completed.
