### ISSUE TITLE
[Bug]: Font URL are unencoded

### ISSUE THREAD

**Issue by Ben-Brady** [juxtopposed/realtimecolors#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The font imports in the exported css do not encode whitespace, this messes with some CSS minifiers and tools because whitespace in URLs is possible non-standard (I'm not really sure, but MDN recommends against it, https://developer.mozilla.org/en-US/docs/Web/CSS/url#string).

### Reproduction Steps

1. Go to 'https://www.realtimecolors.com/?fonts=Noto%20Serif%20Georgian-Noto%20Serif%20Georgian'
2. Click on 'export'
3. Look at the css font @import

### Expected behavior

URL spaces would be encoded as %20

### Device Info

OS Windows 10
Browser; Firefox
Version: 120

**Comment by juxtopposed** [comment]
This should be resolved now (in v3.5)
